title: starrysy
email: songlinyang30@gmail.com
description: >-
  Personal portfolio and blog.
baseurl: ""
url: "https://starrysy.github.io"
github_username: starrysy

theme: minima
minima:
  skin: classic

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
